name: Check linter in PRs
on:
  pull_request:
    types: [opened,edited,reopened,synchronize]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm install
      - name: Run Prettier
        run: pnpm run format
      - name: Run linter
        run: pnpm run lint