name: Check linter in PRs
on:
  pull_request:
    types: [opened,reopened,synchronize]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run Prettier
        run: yarn run format
      - name: Run linter
        run: yarn run lint